debug: false
# used for development only - not supported in production
devMode: false
driver: "aliyun"

image:
  repository: rancher/rancher-csp-adapter
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""

tolerations: []

# if rancher is using a privateCA, this certificate must be provided as a secret in the adapter's namespace - see the
# readme/docs for more details
#additionalTrustedCAs: true

# at least one csp must be enabled like below
aws:
  enabled: false
  accountNumber: ""
  roleName: ""

aliyun:
  enabled: true

csp-adapter:
  csp: "aliyun"
